name: Performance Triage Pipeline

on: workflow_dispatch

permissions:
  contents: write

jobs:
  performance-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testplan: [myplan-checkout, myplan-search]
      fail-fast: false
    steps:
      - name: Get the code and files
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JMeter
        run: |
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter test - ${{ matrix.testplan }}
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t ${{ matrix.testplan }}.jmx -l ${{ matrix.testplan }}-result.jtl -e -o html-report-${{ matrix.testplan }}
